tasks:
  - name: install dependencies
    init: |
      pip3 install -r requirements.txt
      pip3 install -e .
      bash install_beta.sh

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
